### ISSUE TITLE
Correct the health API Endpoint

### ISSUE THREAD

**Issue by shadow3x3x3** [No-57/orange-frontstage-api#14]
The Health API Endpoint should be in `/v1/health`, not `/api/v1/products/health`.  

Health APi is not belonged under `products`.

> the base path `/api/v1` should ref #15

**Comment by shadow3x3x3** [comment]
It seems not correct in main branch. Please verify it again, thanks.

Report from @Vince-Ku.

https://github.com/No-57/orange-frontstage-api/blob/09df20426b389661eb1f5969107fa7eb5cb0142a/src/main/java/com/orange/main/products/controller/ProductsController.java#L58-L61

**Comment by asdfg429** [comment]
@Vince-Ku Could you describe about  the situation?

**Comment by Vince-Ku** [comment]
@asdfg429 
✅ https://{domainhost}/api/v1/health
❌ https://{domainhost}/api/v1/products/health

**Comment by asdfg429** [comment]
Thanks. I'll check later.

**Comment by shadow3x3x3** [comment]
This should be fine. Close.
