### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by shadow3x3x3** [No-57/orange-frontstage-api#16]
I already deployed a online Swagger UI. (From no-57/orange-backstage-api#23)

- [Frontstage](http://146.235.17.81:8081/)
- [Backstage](http://146.235.17.81:8080/)

Please try to implement it according to this Spec for frontstage as much as possible. Thanks.

**Comment by Vince-Ku** [comment]
Really appreciate it !!! 
lifesaver is u ~~~~
