### ISSUE TITLE
Frontstage - Distributor related API design

### ISSUE THREAD

**Issue by Vince-Ku** [No-57/orange-frontstage-api#20]
## Feature

Following [Distributor API's](https://github.com/orgs/No-57/projects/1/views/2?pane=issue&itemId=44034083) API design.

## Get Distributor-like API (member-only)

Retrieve all the distributors liked by the logged-in user.

``` shell
<Auth>
GET https://{domainhost}/distributors/like
```
 #### Response
 ``` JSON
 "code": 10100
 "data": [
        { "id": 1},
        { "id": 12},
        { "id": 123},
  ]

``` 

## Add Distributor-like API (member-only)

Add the distributor liked by the logged-in user.

``` shell
<Auth>
POST https://{domainhost}/distributors/{distributor_id}/like
```
 #### Response
 ``` JSON
 "code": 10100
 "data": nil

``` 

## Delete Distributor-like API (member-only)

Delete the distributor liked by the logged-in user.

``` shell
<Auth>
Delete https://{domainhost}/distributors/{distributor_id}/like
```
  ``` JSON
 "code": 10100
 "data": nil

```

**Comment by Vince-Ku** [comment]
@shadow3x3x3  please take a look if available.

**Comment by shadow3x3x3** [comment]
It seems good.
